--cau2
--1)
SELECT NAME, ID FROM S_CUSTOMER  ORDER BY ID DESC;
--2) 
SELECT NAME FROM S_CUSTOMER WHERE ID='23';
--3)
SELECT FIRST_NAME || ' '|| LAST_NAME AS EMPLOYEES,DEPT_ID FROM S_EMP ORDER BY LAST_NAME desc; 
--4) 
SELECT * FROM S_EMP WHERE LAST_NAME LIKE '%S%';
--5)
SELECT USERID,START_DATE FROM S_EMP WHERE TRUNC(START_DATE) BETWEEN TO_DATE('14/05/1990', 'DD/MM/YY') AND TO_DATE('26/05/1991', 'DD/MM/YY');
--6)
SELECT LAST_NAME, SALARY FROM S_EMP WHERE SALARY BETWEEN 1000 AND 2000;
--7)
SELECT LAST_NAME AS EMPLOYEE_NAME, SALARY AS MONTHLY_SALARY FROM S_EMP WHERE DEPT_ID IN (31,42,50) AND SALARY >1350; 
--8)
SELECT LAST_NAME,START_DATE FROM S_EMP WHERE EXTRACT(YEAR FROM START_DATE)=1991;
--9)
SELECT ID,LAST_NAME,COMMISSION_PCT FROM S_EMP WHERE COMMISSION_PCT=15;
--10)
SELECT LAST_NAME,START_DATE,TO_CHAR(ADD_MONTHS(TRUNC(START_DATE,'MM'),6)+8-MOD(TO_NUMBER(TO_CHAR(ADD_MONTHS(TRUNC(START_DATE, 'MM'), 6) + 8, 'D')), 7), 'fmMonth DDth YYYY') AS next_review_date FROM S_EMP;
